config/routes.rb
Rails.application.routes.draw do
  resources :clearance_batches, only: [:index, :create, :show]
  root to: "clearance_batches#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clearance_batch.rb
class ClearanceBatch < ApplicationRecord
  has_many :items

  def total_price_sold
    items.sum(:price_sold)
  end
end

app/models/item.rb
class Item < ApplicationRecord

  # Associations
  belongs_to :style
  belongs_to :clearance_batch

  # Statuses
  enum status: { 
    sellable: 'sellable', 
    not_sellable: 'not_sellable', 
    sold: 'sold', 
    clearanced: 'clearanced' 
  }

  # Queries
  scope :sellable, -> { where(status: 'sellable') }

  statuses.keys.each do |_status|
    # Setter.
    #
    #   item.status = nil
    #
    #   item.set_status_to_sellable
    #   item.status                  #=> "sellable"
    #
    #   item.set_status_to_failed
    #   item.status                  #=> "not_sellable"
    #
    #   item.set_status_to_sold
    #   item.status                  #=> "sold"
    #
    #   item.set_status_to_clearanced
    #   item.status                  #=> "clearanced"
    #
    self.send :define_method, "set_status_to_#{_status}", -> { self.status = _status }
  end

  def sellable?
    status == 'sellable'
  end
end

app/models/style.rb
class Style < ApplicationRecord
  self.inheritance_column = :_type_disabled
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clearance_batches_controller.rb
class ClearanceBatchesController < ApplicationController
  def index
    @clearance_batches  = ClearanceBatch.all
  end

  def show
    @clearance_batch = ClearanceBatch.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
          render pdf: "Batch No. #{@clearance_batch.id}",
          page_size: 'A4',
          template: "clearance_batches/show.html.erb",
          layout: "pdf.html",
          orientation: "Landscape",
          lowquality: true,
          zoom: 1,
          dpi: 75
      end
    end
  end

  def create
    if params[:csv_batch_file].nil?
      flash[:alert] = "Select a csv file to process first!"
      return redirect_to action: :index
    end

    batch_service = ClearanceItemsFromCsvService.new(params[:csv_batch_file].tempfile)
    batch_service.process!

    errors = []

    if batch_service.batch.persisted?
      flash[:notice]  = "Batch created, #{batch_service.items_clearanced_count} items clearanced in batch #{batch_service.batch.id}"
    else
      flash[:alert] = "Batch was not created and no item were clearanced!"
    end

    if batch_service.errors.any?
      errors << "#{batch_service.errors.count} item ids raised errors and were not clearanced"
      batch_service.errors.flatten.each {|error| errors << error }
    end

    if batch_service.items_clearanced_count > 0
      flash[:success] = "#{batch_service.items_clearanced_count} items(s) clearanced! Check report"
    end

    flash[:alert] = errors.join("<br/>") if errors.any?
    redirect_to action: :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clearance_batches/index.html.erb
<h3>Clearance Batches</h3>

</br>

<%= form_tag(clearance_batches_path, multipart: true, class: 'form-inline', role: 'form') do %>
  <div class="form-group">
    <%= label_tag 'csv_batch_file', 'Select batch file' %>
    <%= file_field_tag 'csv_batch_file', class: 'form-control' %>
  </div>
  <%= button_tag 'Process file', class: 'btn btn-primary' %>
<% end %>

</br>

<table class="table table-bordered clearance_batches">
  <thead>
    <tr>
      <th>Item</th>
      <th>Date clearanced</th>
      <th>Number of items clearanced</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%- @clearance_batches.each do |clearance_batch| -%>
      <tr>
        <td>Clearance Batch <%= clearance_batch.id %></td>
        <td><%= clearance_batch.created_at.strftime('%d/%m/%Y') %></td>
        <td><%= clearance_batch.items.count %></td>
        <td><%= link_to 'View Report', clearance_batch_path(clearance_batch, format: :pdf) %></td>
      </tr>
    <%- end -%>
  </tbody>
</table>

app/views/clearance_batches/show.html.erb
<div class="clearance-box">
  <table cellpadding="0" cellspacing="0">
    <tr class="top">
      <td colspan="3">
        <table>
          <tr>
            <td class="title">
              First Circle Inventory
            </td>
            <td>
              Clearance Batch id #: <b><%= @clearance_batch.id %></b>
              <br>
              Created: <b><%= @clearance_batch.created_at.strftime('%d/%m/%Y') %></b>
              <br>
              Status: Processed</span>
            </td>
          </tr>
        </table>
      </td>
    </tr>

    <tr class="heading">
      <td>Item</td>
      <td class="right">Price Sold</td>
      <td class="right">Sold At</td>
      <td></td>
    </tr>

    <% @clearance_batch.items.each do |item| %>
      <tr class="item">
        <td>
          <%= item.style.name %><br>
          <small><%= item.style.type %></small>
        </td>

        <td class="right">
          <%= number_to_currency(item.price_sold) %>
        </td>

        <td class="right">
          <%= item.sold_at.strftime('%d/%m/%Y') %>
        </td>

        <td></td>
      </tr>
    <% end %>

    <tr>
      <td colspan="4"></td>
    </tr>

    <tr class="heading">
      <td colspan="2"></td>
      <td><b>TOTAL:</b></td>
      <td><b><%= number_to_currency(@clearance_batch.total_price_sold) %></b></td>
    </tr>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TakeHomeChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'shared/nav' %>
<div class="container">

  <%- if flash[:notice] -%>
    <div class="alert alert-info" role="alert">
      <%= flash[:notice].html_safe %>
    </div>
  <%- end -%>
  <%- if flash[:success] -%>
    <div class="alert alert-info" role="alert">
      <%= flash[:success].html_safe %>
    </div>
  <%- end -%>
  <%- if flash[:alert] -%>
    <div class="alert alert-danger" role="alert">
      <%= flash[:alert].html_safe %>
    </div>
  <%- end -%>
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PDFs - Ruby on Rails</title>
    <%= wicked_pdf_stylesheet_link_tag "clearance_batch" %>
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">First Circle Inventory Management</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Clearance batches", clearance_batches_path %></li>
    </ul>
  </div>
</nav>